[workspace]
resolver = "2"
members = ["risc0-guests/operator",  "risc0-guests/verifier", "core", "circuits"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
